RA-03
KinCadeFoster/RecipeApp pull request #1
Opened 2024-07-21 03:10 UTC by KinCadeFoster

- Подключил в конфигурации проекта ViewBinding
- В методе onCreate() инициализировал переменную binding и передал в setContentView()
- Реализовал фон основного лейаута в соответствии с цветом макета
- Сверстал кнопки в лейауте, но app:icon нет в стандартных кнопках, пришлось использовать material.button. Не совсем понятно, как реализовать со стандартным Button
- Импортировал в проект шрифт для кнопок - но почему то отличается от макета, видимо что то сделал не то =(
- Стилизовал кнопки, вынес в стили оформление текста кнопок
- Создал стиль StyleNavButton, унаследовал от Widget.Material3.Button. Определил все необходимые атрибуты.
- Окрасил StatusBar и NavigationBar в соответствии с цветом макета
- Вынес в ресурсы паараметры

2024-07-22 05:33 UTC, ievetrovdev requested changes

2024-07-22 05:33 UTC, ievetrovdev commented on app/src/main/java/ru/example/recipeapp/MainActivity.kt
>          enableEdgeToEdge()
Давай уберем enableEdgeToEdge(), чтобы контент активити (и фрагмента) не заезжал на статусбар и навбар.

2024-07-22 05:33 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginStart="16dp"
Не обязательно для каждой стороны прописывать марджины по отдельности. Есть более универсальные атрибуты. 
android:layout_margin=""
android:layout_marginHorizontal=""
android:layout_marginVertical=""

2024-07-22 05:33 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginStart="16dp"
Все значения не забываем выносить в ресурсы и переиспользовать. Размеры элементов/шрифтов, цвета, строки

2024-07-22 05:33 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            <com.google.android.material.button.MaterialButton
Согласно ТЗ для кнопки нужно использовать view из стандартной библиотеки – Button.

2024-07-22 05:33 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        <LinearLayout
Корректнее будет размещать в одном контейнере LinearLayout с горизонтальной ориентацией две кнопки с одинаковым весом. Под каждую кнопку отдельный контейнер делать ненужно – это бессмысленно.

2024-07-22 05:33 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_marginStart="4dp">
Чтобы размер кнопок и расстояние между ними было максимально симметричным – лучше добавить по 2dp в конце первой и в начале второй кнопки.

2024-07-22 05:33 UTC, ievetrovdev commented on app/src/main/res/values/colors.xml
> +    <color name="background_color">#F4FAFF</color>
Повторять значения одних и тех же цветов с разными айдишниками не рекомендуется. Пусть в ресурсах хранятся только уникальные айтемы, а уникализировать значения для разных элементов интерфейса корректнее через кастомные стили.

2024-07-22 05:33 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">14sp</item>
Все размеры и цвета выносим в ресурсы

2024-07-22 05:33 UTC, ievetrovdev commented on app/src/main/java/ru/example/recipeapp/MainActivity.kt
> +    private lateinit var binding: ActivityMainBinding
lateinit - заманчивая конструкция, но опасная и никак не спасающая от NullPointerException. Вот тут Кирилл Розов наглядно объясняет почему лучше избежать использования lateinit по возможности. https://youtu.be/0nXXUzMyF8c

Лучше стараться продумать подходящее поведение по-умолчанию. В уроке я реализовывал backing property (резервное свойство). Но здесь предлагаю применить более элегантный вариант с помощью делегата lazy, который использует ленивую инициализацию. Это такой механизм, который в лямбде принимает в нашем случае inflate() и возвращает созданный объект, который будет создан при первом обращении к нему.

2024-07-22 05:33 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:fontFamily">@font/montserrat_alternates_regular</item>
Согласно макету толщина шрифта для кнопок SemiBold. Нужно добавить соответствующий шрифт.

2024-07-22 05:33 UTC, ievetrovdev commented on app/src/main/res/values/themes.xml
> +        <item name="android:navigationBarColor">@color/colorNavigationBar</item>
Цвет установлен корректно, однако, теперь белое на белом сливается. Есть еще один специальный атрибут, который говорит системе, что это светлый статус/навбар и что шрифт нужно сделать серым.

2024-07-22 19:56 UTC, KinCadeFoster commented on app/src/main/res/layout/activity_main.xml
> +        <LinearLayout
подумал что в маткете именно такая реализация) тоже показалось странным) ну как минимум позанималсся версткой

2024-07-22 19:58 UTC, KinCadeFoster commented on app/src/main/res/layout/activity_main.xml
> +            <com.google.android.material.button.MaterialButton
как применить app:iconGravity к стандартной библиотеки – Button? насколько я понял, нет такой возможности

2024-07-23 11:50 UTC, ievetrovdev requested changes

2024-07-23 11:50 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        <com.google.android.material.button.MaterialButton
а что со второй кнопкой?

2024-07-23 11:50 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="button_margin_end">2dp</dimen>
Повторять одни и те же значения размеров с разными айдишниками не рекомендуется. Пусть в dimens хранятся только уникальные айтемы, а уникализировать значения для разных элементов интерфейса корректнее через кастомные стили.

2024-07-23 11:50 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:lineHeight">16sp</item>
Все выносим в ресурсы

2024-07-23 11:50 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">14sp</item>
не исправлено

2024-07-23 11:50 UTC, ievetrovdev commented on app/build.gradle.kts
> +    implementation("com.google.android.material:material:1.10.0")
Для чего нужна эта библиотека? Материал уже поставляется в сдк

2024-07-23 15:09 UTC, KinCadeFoster commented on app/src/main/res/layout/activity_main.xml
> +        <com.google.android.material.button.MaterialButton
как применить app:iconGravity к стандартной библиотеки – Button? насколько я понял, нет такой возможности

2024-07-24 13:41 UTC, ievetrovdev requested changes

2024-07-24 13:41 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +
лишняя строка

2024-07-24 13:41 UTC, ievetrovdev commented on app/src/main/res/values/colors.xml
> +    <color name="red">#E13E3E</color>
для кастомных цветов предлагаю такой формат названия ресурсов, например main_background_color. "color" в конце обязательно для отделения одного айди ресурса от другого.

2024-07-24 13:41 UTC, ievetrovdev commented on app/src/main/res/values/colors.xml
> +    <color name="background_color">#F4FAFF</color>
Не нужно резолвить самостоятельно треды) тем более, что ошибки не исправлены. Одних и тех же значений ресурсов в ресурсных файлах быть не должно)

2024-07-24 13:41 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="corner_radius">8dp</dimen>
Повтор

2024-07-24 13:41 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="font_weight">600</dimen>
Вес устанавливаем через уникальный импортированный шрифт

2024-07-25 13:03 UTC, ievetrovdev approved these changes
С комментом для следующего ПР

2024-07-25 13:03 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="margin_horizontal">@dimen/common_16dp</dimen>
Здесь хранятся только чистые значения, остальное при необходимости выносится в стили

2024-07-27 18:24 UTC, merged