RA-13
KinCadeFoster/RecipeApp pull request #11
Opened 2024-10-13 16:33 UTC by KinCadeFoster

- Добавил тэг NestedScrollView в качестве основного контейнера
- Реализовал в шапке изображение и название рецепта, стилизовал согласно макету
- Добавил заголовки для секций 'Ингредиенты' и 'Способ приготовления'
- Добавил два контейнера RecyclerView для соответствующих списков (rvIngredients и rvMethod)
- Создал адаптер для ингредиентов IngredientsAdapter и шагов приготовления MethodAdapter
- Реализовал горизонтальный разделитель между элементами списков
- Оптимизировал код

2024-10-13 19:39 UTC, ievetrovdev requested changes

2024-10-13 19:39 UTC, ievetrovdev commented on app/src/main/java/ru/example/recipeapp/RecipeFragment.kt
> +            dividerColor = resources.getColor(R.color.divider_color, null)
Щас есть несколько проблем с divider:
Он занимает полную длину вьюхи, на дизайне такого нет
Для последнего элемента полоса не нужна

Нужно настроить эти параметры
isLastItemDecorated
setDividerInsetStartResource
setDividerInsetEndResource

2024-10-13 19:39 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipe.xml
> +            android:layout_margin="@dimen/margin_16"
Не хватает background ввиде shape другого цвета

2024-10-13 19:39 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipe.xml
> +            android:nestedScrollingEnabled="false"
Не хватает background ввиде shape другого цвета

2024-10-13 19:39 UTC, ievetrovdev commented on app/src/main/res/layout/item_ingredient.xml
> +    android:padding="8dp">
Вынести в ресурсы

2024-10-13 19:39 UTC, ievetrovdev commented on app/src/main/res/layout/item_ingredient.xml
> +        android:id="@+id/tvIngredient"
Шрифт не соответствует дизайну

2024-10-13 19:39 UTC, ievetrovdev commented on app/src/main/res/layout/item_method.xml
> +        android:id="@+id/tvStep"
Шрифт не соответствует дизайну

2024-10-13 19:39 UTC, ievetrovdev commented on app/src/main/res/layout/item_method.xml
> +    android:padding="8dp">
Вынести в ресурсы

2024-10-13 19:39 UTC, ievetrovdev commented on app/src/main/res/layout/item_ingredient.xml
> +        android:text="@string/ingredients" />
Не хватает еще TextView для показа величины и количества

2024-10-13 19:42 UTC, ievetrovdev requested changes

2024-10-13 19:42 UTC, ievetrovdev commented on gradle/libs.versions.toml
> +androidx-legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }
Почему решил добавить эту библиотеку? В ней содержится устаревший legacy код, надо стараться избегать его и не тянуть в новые проекты

2024-10-14 12:36 UTC, KinCadeFoster commented on gradle/libs.versions.toml
> +androidx-legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }
Видимо эксперементировал, осталось, сам не помню в какой момент добавлял

2024-10-16 09:29 UTC, ievetrovdev requested changes

2024-10-16 09:29 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="divider_inset_start">12dp</dimen>
Плохим тоном является дублирование ресурсов, это касается и цветов, и строк, и dimens.  У тебя повторяетсся 12dp, 4dp. Также ссылаться на item и плодить много одинаковых значений тоже не очень правильно. Создай просто common_8dp как dimen и используй во всех местах напрямую.

2024-10-16 14:09 UTC, merged