RA-14
KinCadeFoster/RecipeApp pull request #12
Opened 2024-10-16 18:19 UTC by KinCadeFoster

- сверстал подзаголовок для количества порций и TextView
- добавил тэг SeekBar с атрибутами значений от 1 до 5
- установил setOnSeekBarChangeListener()
- Внутри передаваю объект интерфейса object : SeekBar.OnSeekBarChangeListener {}
- в IngredientsAdapter создал метод updateIngredients()
- Ппри изменении прогресса вызывается во фрагменте созданный метод и передавать значение progress
- в IngredientsAdapter создал переменную quantity и обновляю ее значение при вызове updateIngredients()
- добавить проверку для перемноженного значения на целостность числа
- небольшой рефакторинг

2024-10-16 20:27 UTC, Churickoid requested changes
Какие проблемы из прошлых пр остались:
1) В MethodAdapter не пронумерованы элементы, добавь при присовении текста еще и position+1. 
2) contentDescription для фото из RecipeFragment не устанавливается динамически
3) непонятный строковой ресурс button_recipe, это служебный текст, лучше без ресурсов приши его в tools:text

2024-10-16 20:27 UTC, Churickoid commented on app/src/main/java/ru/example/recipeapp/IngredientsAdapter.kt
> +        val totalQuantity = quantityValue * quantity
Вообще для чисел с точкой лучше использовать BigDecimal. Он позволяет точнее сравнивать и производить вычисления. Плюс есть встроенные методы для форматирования строк. Статья про BigDecimal: https://javarush.com/groups/posts/2274-kak-ispoljhzovatjh-bigdecimal-v-java

val totalQuantity = BigDecimal(ingredientCurrentCount) * BigDecimal(quantity)

val displayQuantity = totalQuantity
.setScale(1,RoundingMode.HALF_UP)
.stripTrailingZeros()
.toPlainString()

2024-10-16 20:27 UTC, Churickoid commented on app/src/main/res/values/dimens.xml
> +    <dimen name="margin_6">@dimen/common_6dp</dimen>
Повторять одни и те же значения ресурсов с разными айдишниками , будь то строки, цвета и dimens, плохая практика. Пусть здесь хранятся только уникальные айтемы, а уникализировать значения для разных элементов интерфейса корректнее через кастомные стили. Просто дай им более обще название по типу common_6dp и используй их в нескольких местах.
А все лишние дубликаты  margin_6 padding_4 и другие надо подчистить
Так для всех ресурсов в этом файле

2024-10-16 20:27 UTC, Churickoid commented on app/src/main/res/values-ru/strings.xml
> +    <string name="portions">Порции:</string>
Рекомендую задавать название ресурса в соответствии с ее назначением, соблюдая единый стиль других айтемов. Чтобы при глобальном поиске по проекту (через `Shift + Ctrl + F`) в выдачу не попадали другие результаты, содержащие этот же текст, и не сбивали с толку.

Лучше уточнить, что это текстовый ресурс с помощью префикса, например, `text_` или `title_`.

2024-10-16 20:27 UTC, Churickoid commented on app/src/main/java/ru/example/recipeapp/RecipeFragment.kt
> +        binding.seekBar.progress = defaultQuantity - 1
В этой строке нету смысла, ты установил значение min = 1 в xml, можно не вычитать единицу эту. А лучше вообще вынести эту строку в xml и прописать android:progress = "1"

2024-10-16 20:27 UTC, Churickoid commented on app/src/main/java/ru/example/recipeapp/RecipeFragment.kt
> +        binding.tVPortionNum.text = defaultQuantity.toString()
Это дефотное значение тоже по хорошему вынести в xml

2024-10-17 09:43 UTC, KinCadeFoster commented on app/src/main/res/values/dimens.xml
> +    <dimen name="margin_6">@dimen/common_6dp</dimen>
надесь все верно)

2024-10-17 11:12 UTC, Churickoid approved these changes
Всё верно, молодец! Оставил один коммент, поправь его, когда будешь делать следующее задании

2024-10-17 11:12 UTC, Churickoid commented on app/src/main/res/layout/fragment_list_recipes.xml
>          app:layoutManager="androidx.recyclerview.widget.GridLayoutManager"
GridLayout нужен только для отрисовок сетки, как на фрагменте Категорий. Давай лучше использовать более простой LinearLayoutManager без указания spanCount

2024-10-17 16:03 UTC, merged