RA-16
KinCadeFoster/RecipeApp pull request #14
Opened 2024-10-19 17:36 UTC by KinCadeFoster

- Экспортировал иконки
- Сверстал кнопку
- Добавил слушатель
- добавил круговой риппл эффект при нажатии на кнопку

2024-10-20 13:38 UTC, Churickoid requested changes
ic_heart_empty_button.png лишний файл, его нужно удалить

2024-10-20 13:38 UTC, Churickoid commented on app/src/main/java/ru/example/recipeapp/RecipeFragment.kt
> +    private lateinit var imageHeartButton: ImageButton
Глобальной эту переменную делать не надо, лучше её убрать вообще. Плюс при неправельном использовании может крашнут приложение , lateinit  лучше избегать, делать первичное значение хотя бы null

2024-10-20 13:38 UTC, Churickoid commented on app/src/main/java/ru/example/recipeapp/RecipeFragment.kt
> +        imageHeartButton.setOnClickListener {
сильно ли это делает код более читаемым?
Или инициализация глобальной переменной, присвоение, а затем только прикрепление listener? Почему бы сразу напрямую не обращаться к элементу через binding?

binding.imageHeartButton.setOnClickListener{}

2024-10-20 13:38 UTC, aGroupoid commented on app/src/main/res/layout/fragment_recipe.xml
> +            android:background="@drawable/ripple_heart_button"
ripple эффект щас не работает, добавь те же параметры как для карточек. Их можно выести в отдельный стиль и переиспользовать

2024-10-20 15:37 UTC, KinCadeFoster commented on app/src/main/java/ru/example/recipeapp/RecipeFragment.kt
> +        imageHeartButton.setOnClickListener {
нет, видимо фрагментное пошаговое мышление)

2024-10-20 16:11 UTC, KinCadeFoster commented on app/src/main/res/layout/fragment_recipe.xml
> +            android:background="@drawable/ripple_heart_button"
потыкал, но что то не то выходит) возможно это бага ОС

2024-10-20 16:23 UTC, KinCadeFoster commented on app/src/main/res/layout/fragment_recipe.xml
> +            android:background="@drawable/ripple_heart_button"
переделал, но почему то не работает, видимо чего то не понимаю

2024-10-20 17:47 UTC, Churickoid commented
Перепроверил прошлую реализацию на своем девайсе, действительно работала. Но на дефолтных эмуляторах pixel она ничего не делает.
Предлагаю сделать так:
 android:foreground="?attr/selectableItemBackgroundBorderless" // можешь прописать старый рипл, должно работать
 android:background="#00000000" // пустой цвет, вынести в ресурсы
С такими параметрами работает и на пикселе, и на моем устройстве

2024-10-20 21:31 UTC, KinCadeFoster commented on app/src/main/res/layout/fragment_recipe.xml
> +            android:background="@drawable/ripple_heart_button"
хотел поменять форму кнопки
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="oval">
    <solid android:color="@android:color/transparent" />
</shape>

но почему то всеравно квадратной остается =(

2024-10-21 08:29 UTC, Churickoid commented on app/src/main/res/layout/fragment_recipe.xml
> +            android:background="@drawable/ripple_heart_button"
ты в foreground прописывал @drawable/ripple_heart_button? Вроде как должно работать так. Ладно, это не критично, главное, что на всех устройствах он есть)

2024-10-21 08:29 UTC, Churickoid approved these changes
Всё верно, молодец!

2024-10-21 19:17 UTC, merged