RA-17
KinCadeFoster/RecipeApp pull request #15
Opened 2024-10-21 20:12 UTC by KinCadeFoster

- Добавил логику сохранения состояния с SharedPreferences.
- Добавил логику обработки состояния из SharedPreferences и установку соответсвующего состояния на краточке рецепта

2024-10-21 21:05 UTC, Churickoid requested changes
Молодец, текущее задание сделал всё верно. Только щас заметил, что у ингридиентов нету велечины измерения как на макете фигма. Поправь в этом ПР эту проблему

2024-10-21 21:05 UTC, aGroupoid commented on app/src/main/java/ru/example/recipeapp/RecipeFragment.kt
> +        isFavorite = favorites.contains(recipe.id.toString())
Выглядит, что эта переменная лишняя. Перед её использованием ты всегда меняешь её значение на новое, может тогда делать это через локальную переменную?

2024-10-21 21:05 UTC, aGroupoid commented on app/src/main/java/ru/example/recipeapp/RecipeFragment.kt
>      private lateinit var ingredientsAdapter: IngredientsAdapter
lateinit - заманчивая конструкция, но опасная и никак не спасающая от NullPointerException. 
Лучше стараться продумать подходящее поведение по-умолчанию. В уроке я реализовывал backing property (резервное свойство). Но здесь предлагаю применить более элегантный вариант с помощью делегата lazy, который использует ленивую инициализацию. Это такой механизм, который в лямбде принимает в нашем случае inflate() и возвращает созданный объект, который будет создан при первом обращении к нему.

2024-10-22 13:52 UTC, KinCadeFoster commented on app/src/main/java/ru/example/recipeapp/RecipeFragment.kt
>      private lateinit var ingredientsAdapter: IngredientsAdapter
у нас же доступа к recipe нет, пока вижу один враиант, передавать в конструктор фрагмента.

2024-10-22 19:45 UTC, Churickoid commented on app/src/main/java/ru/example/recipeapp/RecipeFragment.kt
>      private lateinit var ingredientsAdapter: IngredientsAdapter
В твоём случае лучше тогда просто проинициализировать адаптер сразу с пустым списком. Потом менять его dataSet с актуальным списком в onCreate, если обновление не будет происходить, надо уведомить адаптер об изменениях и вызвать adapter.notifyDataSetChanged().

В конструктор фрагментов ничего передавать не надо, после поворота экрана, фрагмент пересоздастся и все данные из конструктора сотрутся. Ссылаться будет не на что

2024-10-22 19:47 UTC, Churickoid approved these changes
Апрувлю,  поправь в следующем ПР коммент. Еще заметил,  при входе на экран Рецептов - количество порций пустое.  Добавь начальное значение для этой textView

2024-10-23 15:52 UTC, merged