RA-05
KinCadeFoster/RecipeApp pull request #3
Opened 2024-08-06 18:00 UTC by KinCadeFoster

- рефакторинг
- добавлены слушатели для кнопок
- созданы файлы FavoritesFragment.kt и лейаут fragment_favorites.xml, задал стандартный фон, в разметке вывел на экран текст с названием фрагмента
- сделал навигацию по кнопка

2024-08-07 16:52 UTC, ievetrovdev requested changes

2024-08-07 16:52 UTC, ievetrovdev commented on app/src/main/java/ru/example/recipeapp/CategoriesListFragment.kt
> +    companion object {
А чем руководствовался при добавлении этого companion object с newInstance()? Кроме того функция нигде не используется после объявления. На самом деле эта конструкция здесь в принципе не нужна, созданием фрагмента занимается FragmentManager и под капотом берет на себя всю рутину по инициализации.

2024-08-07 16:52 UTC, ievetrovdev commented on app/src/main/java/ru/example/recipeapp/MainActivity.kt
> +            .replace(binding.mainContainer.id, fragment)
Ты используешь Java метод add/replace из класса FragmentTransaction.java (посмотри его декларацию). Документация же предлагает импользовать Kotlin extension функцию add() из класса FragmentTransaction.kt. 

Именно для импорта метода add/replace нужно было имплементировать библиотеку fragment-ktx. Экстеншн подразумевает принудительное указание типа, а второй параметр с созданием экземпляра фрагмента уже не нужен.

2024-08-07 16:58 UTC, KinCadeFoster commented on app/src/main/java/ru/example/recipeapp/CategoriesListFragment.kt
> +    companion object {
Не знал. Паралельно книжку читал, как раз было про состояние через компаньон. Вот решил заготовку оставить на будущее.

2024-08-08 07:38 UTC, ievetrovdev approved these changes

2024-08-08 07:38 UTC, ievetrovdev commented on app/src/main/java/ru/example/recipeapp/MainActivity.kt
> +    private inline fun <reified T : Fragment> replaceFragment() {
Отличное решение

2024-08-08 08:41 UTC, merged