RA-08
KinCadeFoster/RecipeApp pull request #6
Opened 2024-09-04 18:54 UTC by KinCadeFoster

- Создал файл адаптера CategoriesListAdapter
- Инициализировал RecyclerView во фрагменте CategoriesListFragment
- Убедится, что карточка элемента категории в списке кликабельная
- небольшой рефакторинг

2024-09-05 16:48 UTC, ievetrovdev commented
<item name="android:paddingVertical">@dimen/padding_10</item>
<item name="android:paddingHorizontal">@dimen/padding_10</item>
В таких случаях в стиле лучше указывать просто padding одной строкой

2024-09-05 16:50 UTC, ievetrovdev requested changes

2024-09-05 16:50 UTC, ievetrovdev commented on app/src/main/java/ru/example/recipeapp/CategoriesListAdapter.kt
> +        fun bind(category: Category) {
Работает, но не оптимизировано. ViewHolder должен отвечать только за хранение вьюх, а логика, связанная с изменением данных, должна быть вынесена на уровень адаптера в onBindViewHolder. 
Если заполнить этот список большим объемом данных, RecyclerView создаст примерно 12 viewHolders и будет переиспользовать эти блоки, меняя лишь содержание внутри в функции onBindViewHolder. Сейчас у тебя viewHolder пустой и этой магии не происходит, просто вынесена вся логика из onBindViewHolder в функцию bind.

2024-09-05 16:50 UTC, ievetrovdev commented on app/src/main/java/ru/example/recipeapp/CategoriesListAdapter.kt
> +                val drawable = Drawable.createFromStream(
это должно выполняться в onBindViewHolder

2024-09-05 16:50 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> -    <style name="StyleNavButton" parent="Widget.Material3.Button">
выше убрал правильно, а вот здесь не надо. Мы наследуемся от кнопки из materialDesign

2024-09-05 19:24 UTC, KinCadeFoster commented on app/src/main/res/values/styles.xml
> -    <style name="StyleNavButton" parent="Widget.Material3.Button">
я тут на баг нарвался, на Honor 200 pro. Почему то цвет не устанавливался (был фиолетовый). Все голову сломал, код перепахал, разработчиков подтянул. В конечном итоге выяснилось что это девайс специфик баг, на Pixel 5 и эмуляторах цвет кнопок корректный. При установке цвета явно в кнопке, все нормально становится, если через стиль, то все так же, цвет текста кнопок не по дизайну. В конечном итоге по результатам теста, parent="Widget.Material3.Button" как будь то ни на что вообще не влияет и поэтому снес.

2024-09-06 19:46 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> -    <style name="StyleNavButton" parent="Widget.Material3.Button">
В твоём случае да, параметр "Widget.Material3.Button" ставится по дефолту, поскольку базовая тема твоего приложения наследуется от parent="Theme.Material3.DayNight.NoActionBar". У новых приложений это по дефолту установлено, однако у приложений чуть постарше часто бывают свои кастомные темы, или просто используют Material2, в таких случаях лучше прописывать. В целом можно и убрать.

2024-09-06 19:50 UTC, ievetrovdev approved these changes
Молодец, ставлю апрув. Из коммента не совсем понял, в итоге баг удалось поправить? И в чём баг заключается конкретно: цвет букв или цвет самой кнопки не тот?
Отпиши в личку по этой проблеме, помогу решить, если остался баг

2024-09-07 17:16 UTC, merged