RA-11
KinCadeFoster/RecipeApp pull request #9
Opened 2024-10-07 22:01 UTC by KinCadeFoster

- Создал приватную переменную burgerRecipes и проинициализировал приложенным к story замоканным списком рецептов
- Создал публичный метод getRecipesByCategoryId(), который принимает categoryId -Скачал из макета в Figma изображения 8 рецептов и поместил их в assets
- Сверстал шапку экрана RecipesListFragment, используя переданные во фрагмент ссылку на изображение
- Реализовал список рецептов, используя RecyclerView
- Добавил callback клика на карточку с рецептом. При клике передавать recipeId
- Создал фрагмент RecipeFragment без верстки
- Создал метод навигации openRecipeByRecipeId() на фрагмент с рецептом, принимающий параметр id рецепта

2024-10-09 06:13 UTC, ievetrovdev requested changes

2024-10-09 06:13 UTC, ievetrovdev commented on app/src/main/assets/burger-avocado.png
Картинки выгрузил не исходные, а из экрана – закругленные уже. Закруглять углы будем программно) В макете нужные изображения хранятся в секции с компонентами.

2024-10-09 06:13 UTC, ievetrovdev commented on app/src/main/java/ru/example/recipeapp/RecipeFragment.kt
> +    private var recipeIngredients: List<Ingredient>? = null
Все эти данные хранятся в объекте рецепта. А вот рецепт мы получаем из базы по его айди

2024-10-09 06:13 UTC, ievetrovdev commented on app/src/main/java/ru/example/recipeapp/RecipesListFragment.kt
> +            val bundle = bundleOf(
Согласно ТЗ не нужно сейчас реализовывать передачу данных. А делать это будем не по отдельным полям, а сразу передадим объект рецепта целиком.

2024-10-09 06:13 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_list_recipes.xml
> +            android:layout_marginStart="16dp"
Все значения выносим в ресурсы.

2024-10-09 06:13 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_list_recipes.xml
> +        android:layout_marginTop="8dp"
Вообще все

2024-10-11 04:46 UTC, KinCadeFoster commented on app/src/main/assets/burger-avocado.png
картинки отличались, поэтому взял из экрана. обновил.

2024-10-11 18:47 UTC, ievetrovdev approved these changes
Всё поправил! Молодец!

2024-10-12 03:35 UTC, merged